# Generated by Django 5.2.17 on 2026-09-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], default='undergraduate', max_length=20),
        ),
    ]
